# docker-compose.override.yml (Development additions)

services:
  backend:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
      target: development
    ports:
      - "8000:8000" # Expose the backend port for local testing
    volumes:
      - ./app:/code/app            # Mount local code for live-reloading
      - ./config:/code/config
      - ./shared:/code/shared
      - ./db:/code/db
    # You could also change the CMD here to use the --reload flag for dev
    # command: ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--reload", "-b", "0.0.0.0:8000"]

  frontend:
    volumes:
      - ./frontend:/code/frontend # Mount local code for live-reloading
      - ./config:/code/frontend/config
      - ./shared:/code/frontend/shared

  db:
    ports:
      - "5432:5432" # Expose the DB port for connecting with pgAdmin

  chromadb:
    ports:
      - "8001:8000" # Expose the Chroma port for debugging/fron